server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  include /etc/nginx/mime.types;

  types {
    application/wasm wasm;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
  
  location ~* \.(wasm|js|mjs|worker\.js)$ {
    add_header Cross-Origin-Resource-Policy cross-origin;
    try_files $uri =404;
  }
}
