server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  include /etc/nginx/mime.types;

  # IMPORTANT: correct wasm type
  types {
    application/wasm wasm;
  }

  # DO NOT break assets
  location /assets/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  # normal files
  location / {
    try_files $uri $uri/ /index.html;
  }
}
